### ISSUE TITLE
make the project easier to demo CI / CD

### ISSUE THREAD

**Issue by jstrachan** [snowdrop/spring-boot-http-booster#42]
to try demonstrate CI / CD its nice to make a small change in the source and show how it triggers a new pipeline then you can test out the app and see a different experience running after the pipeline has run.

the current structure of the code with the message `Hello, %s` being in one file then repeated in the test cases; means you have to edit 2 test case assertions and the greetings class just to make a trivial change to demonstrate making a change. This is kinda error prone when giving demos (and you need to generate a PR in github, edit on the PR branch then merge in a single PR ;)

It might be nice to share a constant somewhere for `Hello, %s` so that there's one simple place we can make a change then not have the tests barf?

**Comment by cmoulliard** [comment]
> the current structure of the code with the message Hello, %s being in one file then repeated in the test cases;

The property `greeting.message` can be defined within the application.properties or application.yaml file

```
greeting.message=Hello, %s
```

Do you need something else @jstrachan ?

**Comment by jstrachan** [comment]
I want an easy way to edit the existing java source in the generated project; not add a new file that doesn't exist yet.  So was hoping I could just edit the "Hello, %s" string in one place and have the tests still pass.

e.g. here's the commits I did:
https://github.com/jstrachan/demosb2/commits/master

sure, we could add an application.properties file, but its kinda nicer in a demo to change Java code that exists and is browsable in github/Che really

**Comment by jstrachan** [comment]
BTW the vertx app had a similar issue and has just been fixed to share the default greeting expression between the java + test case: https://github.com/openshiftio-vertx-boosters/vertx-http-booster/issues/2#issuecomment-303326766

**Comment by cmoulliard** [comment]
@gytis Can you have a look to the change made by [Clément for Vert.x ](https://github.com/openshiftio-vertx-boosters/vertx-http-booster/commit/521fc14c5ee89b0ef797bca98fddbf59983b9ddf) to use the same logic as requested by James ?

**Comment by gytis** [comment]
@jstrachan I assume you want the same change in other boosters too?

**Comment by gytis** [comment]
@jstrachan here's the PR: https://github.com/snowdrop/spring-boot-http-booster/pull/43. Will merge once you agree.

**Comment by jstrachan** [comment]
@gytis yeah it'd be great if you could - would make them easier to use in demos of CI / CD / rolling upgrades etc
