### ISSUE TITLE
licenses.xml - invalid The JSON License

### ISSUE THREAD

**Issue by RadekKoubsky** [snowdrop/spring-boot-http-booster#53]
The following dependency within src/licenses/licenses.xml:
````
<dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20140107</version>
      <licenses>
        <license>
          <name>The JSON License</name>
          <url>http://www.json.org/license.html</url>
        </license>
      </licenses>
    </dependency>
````
contains a license with name The The JSON License that does not match any license within
the rh_license_list.json file. 

I think the name "The JSON License" within licenses.xml coressponds with this record within the rh_license_list.json file:
````
"JSON License": {
        "fedora_abbrev": "", 
        "fedora_name": "JSON License", 
        "id": "286", 
        "license_text": "", 
        "rh_approved": "no", 
        "spdx_abbrev": "JSON", 
        "spdx_name": "JSON License", 
        "url": "http://www.json.org/license.html"
    }
```` 

Thus, we might need another fix within license-fix.xsl file, WDYT?

**Comment by RadekKoubsky** [comment]
cc @gytis

**Comment by gytis** [comment]
Fixed: https://github.com/snowdrop/spring-boot-http-booster/commit/19a3dcf755b040ac9cc6d5620cadeb23c1745aa5

**Comment by gytis** [comment]
@RadekKoubsky I've closed this issue as license not is found. However it is not approved, so test still fails.
