### ISSUE TITLE
licenses.xml - invalid The 3-Clause BSD License

### ISSUE THREAD

**Issue by RadekKoubsky** [snowdrop/spring-boot-http-booster#54]
The following dependency within src/licenses/licenses.xml:
````
<dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
      <version>5.0.3</version>
      <licenses>
        <license>
          <name>The 3-Clause BSD License</name>
          <url>https://opensource.org/licenses/bsd-3-clause</url>
        </license>
      </licenses>
    </dependency>
````
contains license with name The 3-Clause BSD License that does not match any license within the http://git.app.eng.bos.redhat.com/git/jboss-licenses.git/plain/rh_license_list.json file

**Comment by gytis** [comment]
Fixed: https://github.com/snowdrop/spring-boot-http-booster/commit/19a3dcf755b040ac9cc6d5620cadeb23c1745aa5

**Comment by gytis** [comment]
@RadekKoubsky Test doesn't assert escaped quotes correctly. JSON file has 'BSD 2-clause \"Simplified\" License' while licenses.xml has 'BSD 2-clause "Simplified" License' and test fails.
