### ISSUE TITLE
new release / git tag 

### ISSUE THREAD

**Issue by rawlingsj** [snowdrop/spring-boot-http-booster#59]
What's the process of generating a new release / git tag?  On OSIO we'e after this PR that was merged 20 days ago https://github.com/snowdrop/spring-boot-http-booster/pull/56

**Comment by rawlingsj** [comment]
Is this repo being maintained?

**Comment by gytis** [comment]
@rawlingsj yes, but we use the JIRA for the issues. Is a new tag all you need?

**Comment by rawlingsj** [comment]
@gytis I believe so yes

**Comment by gytis** [comment]
We'll tag it today

**Comment by rawlingsj** [comment]
thanks

**Comment by cmoulliard** [comment]
@gytis Can you review this PR and take decision please ?
