### ISSUE TITLE
Memory limit in .yaml file causes problems

### ISSUE THREAD

**Issue by quintesse** [snowdrop/spring-boot-http-booster#60]
The [deployment.yml](https://github.com/snowdrop/spring-boot-http-booster/blob/master/src/main/fabric8/deployment.yml) fragment which gets copied to the [application.yml](https://github.com/snowdrop/spring-boot-http-booster/blob/v9/.openshiftio/application.yaml#L201) causes problems on some OpenShift clusters (notably online-stg.openshift.com) that set a _higher_ minimum!

(The online-stg.openshift.com server does not allow you to use a lower value than 255 for example, if you do the pod fails to start)

So is this limit necessary? Can't we remove it? Because whatever value we choose there will probably always be a risk that it's the wrong value?

**Comment by quintesse** [comment]
@cmoulliard none of the other boosters do this so I don't know the answer :)

Personally I think it should be considered a bug that OpenShift lets an application fail because it's asking for too _little_ memory. It makes no sense at all., it should just automatically raise that value to the minimum supported by the server/cluster settings.

**Comment by cmoulliard** [comment]
This limit has been added for OSIO - See commit : https://github.com/snowdrop/spring-boot-http-booster/commit/271136427ab220824727a17e547905c577e57704
@rawlingsj Can we adapt the limit to be able to cover OSIO + LOSIO use cases ?

**Comment by spisiakm** [comment]
@cmoulliard @quintesse we had a simliar issue on Vert.x side. The limit was in place so more apps could run in restricted OSIO environment, but this would cause the app to fail on OSO (as you mentioned, because the mem limit was too low). We just removed the `deployment.yml` file altogether.

**Comment by Ladicek** [comment]
I'd very much recommend to remove the `deployment.yml` file as well. With these settings, the application fails to deploy in the boosters CI environment, because the pod keeps being restarted, because it fails to start with this message: `Terminated at Feb 22, 2018 7:45:36 PM with exit code 137 (OOMKilled)`

**Comment by geoand** [comment]
I also witnessed this problem when I tried to test the app today on one of
the Dev clusters (although it worked fine on my Minishift cluster).

+1 for fixing it!

**Comment by cmoulliard** [comment]
I agree to remove such limit as it only concerns OSIO. As they install the booster using FMP, then such yaml fragment could added during the process to create the DC
