### ISSUE TITLE
dropped f8-m-p from application

### ISSUE THREAD

**Issue by hrishin** [snowdrop/spring-boot-http-booster#65]
Hey @gytis 

Recent [changes](https://github.com/snowdrop/spring-boot-http-booster/commit/b14a44fae6418057af2bc6a21144fdffcde322ab#diff-600376dffeb79835ede4a0b285078036L156) has dropped f8-m-p from application `pom.xml`. Is it desired? I'm just wondering why?

https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/rest-http/spring-boot/redhat/spring-boot-rest-http-redhat.yaml

**Comment by cmoulliard** [comment]
@hrishin It is dropped but moved to the parent Spring Booster POM [file](https://github.com/snowdrop/spring-boot-booster-parent/blob/master/pom.xml). Is it an issue for you ?

**Comment by hrishin** [comment]
@cmoulliard ahh thanks for the update.

**Comment by cmoulliard** [comment]
@hrishin Can we close the issue then ?

**Comment by cmoulliard** [comment]
@gytis Can you review this PR and take decision please ?
