### ISSUE TITLE
Skipping Arquillian Openshift Integration Tests in pipeline

### ISSUE THREAD

**Issue by dipak-pawar** [snowdrop/spring-boot-http-booster#66]
From [Jenkinsfile](https://github.com/snowdrop/spring-boot-http-booster/blob/master/Jenkinsfile#L4) we are not running openshift integration tests in pipeline. 

@ALRubinger, @gytis Do we have any reason to skip integration tests?

**Comment by cmoulliard** [comment]
@gytis Can you review this PR and take decision please ?

**Comment by gytis** [comment]
The jenkinsfile is not used any more, we'll just remove it.
