### ISSUE TITLE
OpenShiftIT Test Fails Out of the Box

### ISSUE THREAD

**Issue by sherl0cks** [snowdrop/spring-boot-http-booster#74]
https://github.com/snowdrop/spring-boot-http-booster/blob/master/src/test/java/io/openshift/booster/OpenShiftIT.java

```
$ mvn verify -Popenshift-it

...

[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.566 s <<< FAILURE! - in io.openshift.booster.OpenShiftIT
[ERROR] testGreetingEndpointWithNameParameter(io.openshift.booster.OpenShiftIT)  Time elapsed: 0.62 s  <<< ERROR!
java.lang.RuntimeException: Could not set RouteURL value on field private java.net.URL io.openshift.booster.OpenShiftIT.baseURL
Caused by: java.lang.IllegalArgumentException: Could not resolve route: assistant. Available routes: []

[ERROR] testGreetingEndpoint(io.openshift.booster.OpenShiftIT)  Time elapsed: 0.155 s  <<< ERROR!
java.lang.RuntimeException: Could not set RouteURL value on field private java.net.URL io.openshift.booster.OpenShiftIT.baseURL
Caused by: java.lang.IllegalArgumentException: Could not resolve route: assistant. Available routes: []
```

**Comment by geoand** [comment]
Hi @sherl0cks,

Thanks for checking this out! I am not seeing this error, either when running the tests locally or in the RHOAR CI (http://rourka.op.redhat.com/).

Can you please provide some more details about the Openshift environment you are using?

Also note that the correct command to execute the tests is:
`mvn verify -Popenshift,openshift-it`

Thanks

**Comment by sherl0cks** [comment]
That works. Can we get the docs updated so users don't need to drive through parents poms to find this information?

**Comment by sherl0cks** [comment]
I'm referring to the README.adoc produced in the .zip I got from launcher. I'll be honest, I've never seen or used the docs you are referencing. Looks like its nestled nicely at the last line of that README. It's possible the issue is with https://launch.openshift.io/ then, as I don't see this README in this repo?

**Comment by sherl0cks** [comment]
Here is that zip for reference.
[assistant.zip](https://github.com/snowdrop/spring-boot-http-booster/files/1876865/assistant.zip)

**Comment by geoand** [comment]
The README you are referring to is definitely not included in this repo, the thing is that I don't really know were it's coming from :)

@inoxx03 Do you have any idea about the documentation issue that @sherl0cks is mentioning above?

**Comment by sherl0cks** [comment]
@geoand what fun - launcher & boosters is turning out to be on heck of a rabbit hole...

**Comment by geoand** [comment]
There are definitely issues that need to be worked out, but I would say
that the launcher does give one a lot out of the box 😀

**Comment by sherl0cks** [comment]
Yes indeed, it's really promising. But the paper cut bugs I'm hitting right now are quite painful.

**Comment by geoand** [comment]
I read you!

I'll do what I can on my part to get this heard.

Thanks for your feedback

**Comment by inoxx03** [comment]
@geoand About the README that @sherl0cks is referring to:
The launcher generates booster-specific README files that are displayed in the launcher UI (or included in the downloadable ZIP with the booster sources, depending which option you choose) when you deploy a booster. These boosters are part of the launcher and not are not included the runtime documentation. The content of these READMEs is dynamically generated based on a [template](https://github.com/fabric8-launcher/launcher-documentation/blob/master/docs/topics/readme/rest-http-README.adoc)  and a set of [properties](https://github.com/fabric8-launcher/launcher-documentation/blob/master/docs/topics/readme/cd-rest-http-spring-boot.properties) appropriate to the deployment type you choose. It seems we we need to update the properties to include the correct command to tun the integration tests.
@sherl0cks Thank you for looking into this.

**Comment by geoand** [comment]
Thanks for the thorough analysis!

**Comment by inoxx03** [comment]
@geoand no problem at all:) I have filed [RHAORDOC-1227](https://issues.jboss.org/browse/RHOARDOC-1227) to track this update.

**Comment by geoand** [comment]
Great, thanks!

**Comment by sherl0cks** [comment]
@inoxx03 thank you very much!
